name = "Jlkep"
uuid = "ea1dc8b9-140f-476a-9e4b-2e3070ddff7f"
authors = ["TsumanumaSakuto <tsumanumasakuto@gmail.com>"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
