name = "Jlkep"
uuid = "ea1dc8b9-140f-476a-9e4b-2e3070ddff7f"
authors = ["TsumanumaSakuto <tsumanumasakutok@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
